---
glob: "**/*.{html,html.erb,turbo_stream.erb}"
linters:
  Rubocop:
    enabled: true
    rubocop_config:
      inherit_from:
        - .standard.yml
      Layout/InitialIndentation:
        Enabled: false
      Layout/TrailingEmptyLines:
        Enabled: false
      Layout/TrailingWhitespace:
        Enabled: false
      Naming/FileName:
        Enabled: false
      Style/FrozenStringLiteralComment:
        Enabled: false
      Lint/UselessAssignment:
        Enabled: false
  RequireInputAutocomplete:
    enabled: true
